name: Release

on:
  push:
    tags: [v*]

jobs:
  release:
    runs-on: self-hosted
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.15
  
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Build and push Docker image
      shell: bash
      run: earthly --push +docker-all --KUBE_VERSION=${{ github.ref_name }}

    - name: Save Images
      run: earthly +save-images-all --KUBE_VERSION=${{ github.ref_name }}

    - name: Upload
      shell: bash
      env:
        UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
      run: |
        upload_file() {
          curl --http1.1 -fSs -H "Authorization: Bearer ${UPLOAD_TOKEN}" -F "file=@$1" https://download.koopt.sh/blob
        }

        echo '# K3S Debian ${{ github.ref_name }}' > release.md

        echo '## Base Image' >> release.md
        URL=$(upload_file dist/k3s-debian-amd64.tar.zst)
        echo "* [k3s-debian-amd64.tar.zst](${URL})" >> release.md
        URL=$(upload_file dist/k3s-debian-arm64.tar.zst)
        echo -e "* [k3s-debian-arm64.tar.zst](${URL})\n" >> release.md

        echo '## Images Archive' >> release.md
        URL=$(upload_file dist/k3s-images-amd64.tar.zst)
        echo "* [k3s-images-amd64.tar.zst](${URL})" >> release.md
        URL=$(upload_file dist/k3s-images-arm64.tar.zst)
        echo "* [k3s-images-arm64.tar.zst](${URL})" >> release.md
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release.md
        files: |
          dist/checksums.txt
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
