name: Release

on:
  push:
    tags: [v*]

jobs:
  release:
    runs-on: self-hosted
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.15
  
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Build and push Docker image
      shell: bash
      run: earthly --push +docker-all --VERSION=${{ github.ref_name }}

    - name: Save Images
      run: earthly +save-images-all --VERSION=${{ github.ref_name }}
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
